import os

WINDOW_TITLE = "Уроборус"
WINDOW_WIDTH = 920
WINDOW_HEIGHT = 1010
WINDOW_MIN_WIDTH = 760
WINDOW_MIN_HEIGHT = 700

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODELS_DIR = os.path.join(PROJECT_ROOT, "models")
ASCII_MODEL_CACHE_DIR = os.path.join(MODELS_DIR, "ascii_cache")
ASCII_DETECTOR_NAME = "detector.onnx"
ASCII_RECOGNITION_NAME = "recognition.onnx"

BUFFALO_ARCHIVE_URL = "https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_s.zip"
BUFFALO_ARCHIVE_NAME = "buffalo_s.zip"
YUNET_MODEL_URL = "https://github.com/opencv/opencv_zoo/raw/main/models/face_detection_yunet/face_detection_yunet_2023mar.onnx"
YUNET_MODEL_NAME = "face_detection_yunet_2023mar.onnx"
YUNET_DOWNLOAD_LABEL = "Детектор"
RECOGNITION_DOWNLOAD_LABEL = "Архив моделей"

RECOGNITION_PREFERRED_SUBSTRING = "mbf"
RECOGNITION_FALLBACK_SUBSTRING = "r50"
ONNX_EXTENSION = ".onnx"

ONNX_PROVIDERS = ("CUDAExecutionProvider", "CPUExecutionProvider")
ONNX_INTRA_THREADS = 4
ONNX_LOG_SEVERITY_ERROR = 3
DEVICE_LABEL_GPU = "GPU"
DEVICE_LABEL_CPU = "CPU"
DEVICE_LABEL_NONE = "-"

EPS = 1e-9
MIN_DT = 0.001
BYTES_IN_MB = 1048576
ASCII_LIMIT = 128

DETECT_SCORE_THRESHOLD = 0.5
DETECT_NMS_THRESHOLD = 0.3
DETECT_TOP_K = 5000
DETECT_BACKEND_DEFAULT = 0
DETECT_TARGET_CPU = 0
DETECT_DEFAULT_WIDTH = 640
DETECT_DEFAULT_HEIGHT = 480
MIN_FACE_WIDTH = 48
MIN_FACE_HEIGHT = 48

FACE_CROP_SIZE = 112
ARCFACE_TEMPLATE = (
    (38.2946, 51.6963),
    (73.5318, 51.5014),
    (56.0252, 71.7366),
    (41.5493, 92.3655),
    (70.7299, 92.2041),
)
WARP_BORDER = (0, 0, 0)
PIXEL_NORM_MEAN = 127.5
PIXEL_NORM_DIV = 127.5

GREEN_THRESHOLD_DEFAULT = 0.50
YELLOW_THRESHOLD_DEFAULT = 0.34
THRESHOLD_SLIDER_MIN = 0.20
THRESHOLD_SLIDER_MAX = 0.80
THRESHOLD_SLIDER_STEP = 0.01
THRESHOLD_MIN_GAP = 0.05
YELLOW_BONUS_MASKED = 0.05
NO_MATCH_INDEX = -1
MIN_COSINE = -1.0

YAW_PROFILE_DEGREES = 35.0
YAW_GAIN = 95.0
YAW_MAX = 90.0
MIN_EYE_DIST = 1.0

OCCLUDE_SKIN_RATIO = 0.22
OCCLUDE_REGION_TOP = 56
OCCLUDE_REGION_BOTTOM = 104
OCCLUDE_REGION_LEFT = 20
OCCLUDE_REGION_RIGHT = 92
SKIN_CR_MIN = 133
SKIN_CR_MAX = 173
SKIN_CB_MIN = 77
SKIN_CB_MAX = 127
CHANNEL_MIN = 0
CHANNEL_MAX = 255

TRACK_IOU_MATCH = 0.35
TRACK_MAX_MISSING = 10
SCORE_SMOOTH_ALPHA = 0.35
RECOGNIZE_EVERY_FRAMES = 6
REFRESH_MOVE_RATIO = 0.15
MAX_REFERENCES = 8
REFERENCE_DETECT_WIDTH = 1280
THUMB_SIZE = 96
FLIP_HORIZONTAL = 1

LIVENESS_START = 0.5
LIVENESS_SMOOTH_ALPHA = 0.25
LIVENESS_SPOOF_BELOW = 0.35
LIVENESS_LIVE_ABOVE = 0.55
LIVENESS_BORDER_CAP = 0.2
LIVENESS_BORDER_STRONG = 0.75
LIVENESS_STATIC_MOTION = 0.25
LIVENESS_FLAT_TEXTURE = 0.4
LIVENESS_STATIC_FLAT_CAP = 0.45
WEIGHT_MOTION = 0.30
WEIGHT_TEXTURE = 0.15
WEIGHT_MOIRE = 0.20
WEIGHT_BORDER = 0.20
WEIGHT_SPECULAR = 0.05
WEIGHT_EYE = 0.10
NEUTRAL_CUE = 0.5

MOTION_HISTORY = 45
MOTION_MIN_FRAMES = 10
MOTION_LOG_LOW = -5.0
MOTION_LOG_HIGH = -2.6
MOTION_SCORE_LOW = 0.15
MOTION_SCORE_HIGH = 0.9

TEXTURE_CENTER_TOP = 20
TEXTURE_CENTER_BOTTOM = 92
TEXTURE_CENTER_LEFT = 20
TEXTURE_CENTER_RIGHT = 92
TEXTURE_SOFT = 30.0
TEXTURE_GOOD = 120.0
TEXTURE_GREAT = 800.0
TEXTURE_NOISY = 2500.0
TEXTURE_SCORE_MIN = 0.15
TEXTURE_SCORE_MID = 0.75
TEXTURE_SCORE_MAX = 0.9
TEXTURE_SCORE_NOISY = 0.4

MOIRE_SIZE = 64
MOIRE_LOW_RADIUS = 8
MOIRE_RING_INNER = 12
MOIRE_RING_OUTER = 28
MOIRE_PEAK_SIGMA = 3.0
MOIRE_PEAK_NORM = 12.0
MOIRE_RATIO_BASE = 0.55
MOIRE_RATIO_SPAN = 0.5
MOIRE_STRONG_AT = 0.45
MOIRE_PEAK_WEIGHT = 0.6
MOIRE_RATIO_WEIGHT = 0.4

BORDER_EXPAND = 1.6
BORDER_CANNY_LOW = 80
BORDER_CANNY_HIGH = 200
BORDER_HOUGH_THRESHOLD = 60
BORDER_MAX_LINE_GAP = 10
BORDER_LINE_RATIO = 1.2
BORDER_BANDS = 4
BORDER_BAND_TOP = 0
BORDER_BAND_BOTTOM = 1
BORDER_BAND_LEFT = 2
BORDER_BAND_RIGHT = 3
BAND_EDGE = 0.25
HOUGH_RHO = 1
HOUGH_LINE_DIM = 4

SPECULAR_VALUE_MIN = 245
SPECULAR_SAT_MAX = 30
SPECULAR_MILD = 0.01
SPECULAR_BAD = 0.08
SPECULAR_SCORE_BAD = 0.2

EYE_CROP_WIDTH = 28
EYE_CROP_HEIGHT = 18
EYE_HISTORY = 45
EYE_MIN_FRAMES = 12
EYE_RANGE_NORM = 0.6
SOBEL_X_ORDER = 0
SOBEL_Y_ORDER = 1
SOBEL_KERNEL = 3

USE_WINDOWS_BACKEND = os.name == "nt"
CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480
CAMERA_FPS = 30
CAMERA_INDEXES = (0, 1, 2)
CAMERA_FAILS_BEFORE_REOPEN = 30
CAMERA_RETRY_PAUSE = 2.0
FPS_SMOOTH = 0.9
IDLE_SLEEP = 0.05

DISPLAY_WIDTH = 860
DISPLAY_HEIGHT = 645
GUI_POLL_MS = 30
STATS_EVERY_SECONDS = 0.5
PROGRESS_THROTTLE = 0.3
FRAME_QUEUE_SIZE = 1

COLOR_GREEN = (0, 210, 0)
COLOR_YELLOW = (0, 215, 255)
COLOR_RED = (0, 0, 235)
BOX_THICKNESS = 3
LABEL_FONT_SIZE = 16
HINT_FONT_SIZE = 22
LABEL_PAD_X = 6
LABEL_PAD_Y = 4
LABEL_BG = (0, 0, 0)
LABEL_FG = (255, 255, 255)
HINT_BG = (20, 20, 20)
HINT_FG = (255, 255, 255)

COLOR_NAME_GREEN = "green"
COLOR_NAME_YELLOW = "yellow"
COLOR_NAME_RED = "red"

VERDICT_SPOOF = "spoof"
VERDICT_UNCERTAIN = "uncertain"
VERDICT_LIVE = "live"

TAG_MASK = "маска"
TAG_PROFILE = "профиль"
TAG_SPOOF = "спуф"

WINDOWS_ARIAL = "C:\\Windows\\Fonts\\arial.ttf"
LINUX_DEJAVU = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"

IMAGE_EXTENSIONS = (".jpg", ".jpeg", ".png", ".bmp", ".webp")

OP_ADD_REF = "add_ref"
OP_REMOVE_REF = "remove_ref"
OP_CLEAR_REFS = "clear_refs"
OP_THRESHOLDS = "thresholds"
OP_CAMERA = "camera"
OP_RETRY = "retry"
OP_STOP = "stop"

EV_STATUS = "status"
EV_STATS = "stats"
EV_MODELS = "models"
EV_REF_ADDED = "ref_added"
EV_REF_ERROR = "ref_error"
EV_REF_REMOVED = "ref_removed"
EV_REFS_CLEARED = "refs_cleared"

MODELS_OK = "ok"
MODELS_FAIL = "fail"

STATUS_START = "Запуск..."
STATUS_DOWNLOAD = "Загрузка моделей..."
STATUS_READY = "Готово. Перетащи фото человека в окно."
STATUS_NO_CAMERA = "Камера не найдена. Проверь подключение."
STATUS_CAMERA = "Камера "
STATUS_REF_ADDED = "Эталон добавлен"
STATUS_REF_LIMIT = "Хватит эталонов, больше не надо"
STATUS_NO_FACE = "На фото нет лица: "
STATUS_BAD_FILE = "Не читается файл: "
STATUS_NOT_IMAGE = "Это не картинка: "
STATUS_REFS_CLEARED = "Эталоны очищены"
STATUS_NO_MODELS_YET = "Модели ещё грузятся, подожди."
STATUS_NO_ORT = "Распознавание недоступно: нет onnxruntime. Перезапусти start.bat."
STATUS_ENGINE_FAIL = "Не получилось запустить модели. Перезапусти программу."
STATUS_BAD_ARCHIVE = "Архив моделей битый. Удали папку models и нажми Повторить."
STATUS_NO_MODEL_IN_ARCHIVE = "В архиве нет модели распознавания. Удали папку models и нажми Повторить."
DOWNLOAD_FAIL_HEAD = "Не получилось скачать "
DOWNLOAD_FAIL_TAIL = ". Проверь интернет и нажми Повторить."
HINT_NO_REFS = "Перетащи сюда фото человека"

LABEL_GREEN = "ОН"
LABEL_YELLOW = "ВОЗМОЖНО"
LABEL_RED = "НЕ ОН"
BUTTON_CLEAR = "Очистить эталоны"
BUTTON_CAMERA = "Камера"
BUTTON_RETRY = "Повторить"
BUTTON_ADD_PHOTO = "Добавить фото"
SLIDER_GREEN = "Зелёный от"
SLIDER_YELLOW = "Жёлтый от"
REFS_TITLE = "Эталоны"
TK_MISSING_MESSAGE = "Нет tkinter. Поставь Python 3.12 с python.org вместе с tcl/tk."
PIL_MISSING_MESSAGE = "Нет Pillow. Запусти start.bat заново."

MB_SUFFIX = " МБ"
SEP_COLON = ": "
SEP_SLASH = " / "
SEP_BAR = " | "
STATS_FPS_SUFFIX = " fps"
STATS_FACES = "лиц: "
STATS_REFS = "эталонов: "

PAD_X = 8
PAD_Y = 6
SLIDER_LENGTH = 170
THUMB_PAD = 4
LEGEND_WIDTH = 12
FG_WHITE = "white"
FG_BLACK = "black"
STATUS_WRAP = 880
DROP_EVENT = "<<Drop>>"
CLICK_EVENT = "<Button-1>"
WM_CLOSE_PROTOCOL = "WM_DELETE_WINDOW"
GEOMETRY_SEPARATOR = "x"
FILES_TITLE = "Картинки"
FILES_MASK = "*.jpg *.jpeg *.png *.bmp *.webp"
PLACEHOLDER_GRAY = 40
